### ISSUE TITLE
watch on windows

### ISSUE THREAD

**Issue by raDiesle** [TypeStrong/grunt-ts#107]
Hi,

 using 11.0.1
I got on win7

Running "ts:watch" (ts) task
[D] Task source: C:\dev\svn\alerting\trunk\src\main\webapp\resources\application\node_modules\grunt-ts\tasks\ts.js
Verifying property ts.watch exists in config...OK
Files: [no src] -> watch
Options: allowBool=false, allowImportModule=false, compile, declaration=false, mapRoot="", module="commonjs", noImplicitAny=false, noResolve=false, co
mments=null, removeComments=null, sourceMap=false, sourceRoot="", target="es5", verbose=false, fast="watch"
Warning: Cannot call method 'indexOf' of undefined Use --force to continue.

Aborted due to warnings.

--> Solved
Reason was, that task ts always needs a subtargettask, 
otherwise it will not work

**Comment by nycdotnet** [comment]
Hi @raDiesle - we've significantly improved our documentation since this issue was reported.  I hope that there are sufficient examples of `gruntfile.js` so that others should not run into this problem.  Thanks for the report.  I'll close this now.  Please let us know if you have any further issues.
