### ISSUE TITLE
Support emitDecoratorMetadata

### ISSUE THREAD

**Issue by Alxandr** [TypeStrong/grunt-ts#244]
Please support the `--emitDecoratorMetadata` flag.

**Comment by nycdotnet** [comment]
Thanks for the suggestion.  We will update for TypeScript 1.5 soon.

**Comment by oliverw** [comment]
@nycdotnet Any ETA for the TS 1.5 update?

**Comment by nycdotnet** [comment]
I've been working on it at night when I have time.  Should be in the next week or so.

In the meantime, you can use a custom TypeScript compiler by following the [instructions here](https://github.com/TypeStrong/grunt-ts#compiler), or just update the reference to TypeScript in your `package.json` to `1.5.0-beta` and re-run `npm install`.

In the downloaded grunt-ts folder in `compile.js`, around line 125, you'll need to add some code.

If you want to just hack it in all the time:
```js
args.push('--emitDecoratorMetadata'); 
```

If you want to get it to work conditionally via the Gruntfile.js (I haven't tested this but you'll get the basic idea).

```js
if (task.emitDecoratorMetadata) { 
    args.push('--emitDecoratorMetadata'); 
} 
```

Then your Gruntfile.js would have to look something like this:

```js
module.exports = function(grunt) {
  grunt.initConfig({
    ts: {
      default : {
        src: ["**/*.ts", "!node_modules/**/*.ts"],
        options: {
            emitDecoratorMetadata: true
        }
      }
    }
  });
  grunt.loadNpmTasks("grunt-ts");
  grunt.registerTask("default", ["ts"]);
};
```

**Comment by nycdotnet** [comment]
I should probably add that the reason this takes a long time is mainly because I want to make sure the tests all still pass and are correct after the compiler upgrade.

Each time we change the underlying TypeScript compiler version, we have to go back though all of our tests to make sure that the changes to the emitted JS are valid based on the parameters we pass (since the TypeScript team doesn't guarantee whitespace consistency between versions, among other things) and sometimes that means either changing tests, changing the parameters passed to the tests, or eliminating/redoing a test that doesn't quite make sense anymore.

Anyway - we try really hard to make sure that this compiler task doesn't have regressions, and as a result it sometimes takes a few sessions to get everything ship-shape.

As part of this 1.5-cycle upgrade I intend to add a feature that would allow passing custom parameters via the Gruntfile directly, so if in TypeScript 1.6, the TS team adds a parameter `--foo`, we can let people put something like `additionalParameters: ['--foo']` in their Gruntfile and it will work as an interim solution.

Thanks for your patience!

**Comment by basarat** [comment]
> As part of this 1.5-cycle upgrade I intend to add a feature that would allow passing custom parameters via the Gruntfile directly, so if in TypeScript 1.6, the TS team adds a parameter --foo, we can let people put something like additionalParameters: ['--foo'] in their Gruntfile and it will work as an interim solution before grunt-ts supports it natively.

Please. Thank you so much :rose: :tada: :gift:

**Comment by nycdotnet** [comment]
FYI: `--emitDecoratorMetadata` is working now in https://github.com/TypeStrong/grunt-ts/pull/246

**Comment by nycdotnet** [comment]
Should be working in 4.2.0-beta.1 which I just pushed to npm, along with the `additionalParameters` feature.  Let me know if it's not working for you.  Thanks for the suggestion.
