### ISSUE TITLE
"experimentalDecorators" is not passed to compiler

### ISSUE THREAD

**Issue by bryanforbes** [TypeStrong/grunt-ts#259]
I'm trying to compile a project using decorators with a recent build of TS and it's telling me that I have to pass the `experimentalDecorators` flag. I can pass it on the command line, in my `tsconfig.json`, but not with `grunt-ts`. I believe it's because it's not handled with the other [boolean options](https://github.com/TypeStrong/grunt-ts/blob/e5503e16716e84df4b4eb1e73703083dfdfb7a1b/tasks/modules/compile.ts#L166-L190).

**Comment by nycdotnet** [comment]
This release of grunt-ts is the one that supports TypeScript 1.5:  https://github.com/TypeStrong/grunt-ts/releases/tag/v4.2.0-beta.1

The docs for it are updated on this branch:  https://github.com/TypeStrong/grunt-ts/tree/update-to-typescript-1.5.0-beta

If the flag name has changed since we released v4.2.0-beta.1, the new version supports passing any arbitrary parameter to tsc via the `additionalFlags` option.  We will update grunt-ts to fully support the final 1.5 compiler once it hits RTM (lots of the new switches have been renamed since we did that work).

Let me know if you have any trouble.

**Comment by bryanforbes** [comment]
I have `grunt-ts@4.2.0-beta.1` installed from npm. I'll try the `additionalFlags` option for now. This flag is different than `emitDecoratorMetadata`, which emits an extra call to `Reflect.metadata`. In order to use decorators at all with the newer 1.5 releases, users are required to pass `--experimentalDecorators` to the compiler or an error will be thrown.

**Comment by nycdotnet** [comment]
It seems that they added `--experimentalDecorators` after we came out with 4.2.0 beta 1.  Thanks for the report.

**Comment by nycdotnet** [comment]
You should be able to pass `experimentalDecorators` in 4.2.0 without having to resort to using `additionalFlags`.  Thanks for the report!!
