### ISSUE TITLE
target option is not working with `vs` when i set it to ES5

### ISSUE THREAD

**Issue by vtkalek** [TypeStrong/grunt-ts#264]
Hi,
i have a gruntFile.js with this grunt-ts config:
```js
grunt.initConfig({
	  
	    ts: {
	        
	        options: {
	            verbose:true,
	            target: 'ES5',
	        },
     default: {
         vs: 'src/clients/visuals/Visuals.csproj'
     }
    },
```

But when i run this task it 's always throws errors like: TS1056 Accessors are only available when targeting ECMAScript 5 and higher.

I check the compiler.ts file installed and found :
args.push('--target', task.target.toUpperCase());
string where target is inserted, but there is alvays es3 value only passed as a target.

I also tried  to add options to default task like this:

```js
	    ts: {
     default: {
         vs: 'src/clients/visuals/Visuals.csproj',
 options: {
	            verbose:true,
	            target: 'ES5',
	        },
     }
```
But it's not working. 

I think it's an issue.

**Comment by seventyone-ben** [comment]
Hey,

ran into the same issue today...

The current version of VS2015/NTVS doesn't seem to write the `<TypeScriptTarget>` tag into the .nsproj by default. The VS2015 default target (at least for me) is ES5.

After changing the targeted ECMAScript version in Visual Studio to ES3 it was present in the project file. Changing it back to ES5 and it was removed again.

It would be great to either make ES5 the default setting in `csproj2ts` or change https://github.com/TypeStrong/grunt-ts/blob/master/tasks/ts.ts#L204-L205 to allow the Gruntfile.js options to override the VS one, and not the other way round, because it will always be ES3 if missing, regardless what you specified in the gruntfile.

I've seen https://github.com/TypeStrong/csproj2ts/issues/6 so you are aware about possible incompatibilities, I just wanted to add my findings/opinion to this issue. If you prefer pull-requests  I could try to free up some time and provide them.

**Comment by nycdotnet** [comment]
Would either of you please update your package.json for grunt-ts to reference csproj2ts 0.0.4 and see if it resolves the issue?  If not, I will take a closer look at this as part of the implementation of tsconfig.json suppor this week.

Thanks for the report.

**Comment by seventyone-ben** [comment]
It still ignores `target:` and `module:`  set in Gruntfile.js, and also `<TypeScriptTarget> ` for me. Other settings from `options` are used (e.g. `verbose`).

Tested with csproj2ts@0.0.4, its default target is ES5, so it's at least compiling for me now.

**Comment by nycdotnet** [comment]
OK thanks.  I should have time to fix this in the next week or so once I implement tsconfig.json support.

**Comment by nycdotnet** [comment]
This will be fixed in #275 when that is complete (still work-in-progress).

**Comment by nycdotnet** [comment]
Hello, @vtkalek  - Would you please try grunt-ts@5.0.0-beta.2 and let me know if it resolves your issue?  Please note that this is a significant rewrite of the options resolution logic so it may have other issues.  Let me know if you see anything.

**Comment by nycdotnet** [comment]
This should be corrected in v5, just released to npm.  Please reopen if not.

**Comment by Drag13** [comment]
Hi, I have almost same problem: 
I have TypeScript 2.0.6.0 (from Help -> About)
and
`"compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "sourceMap": false
  },`

Building with gulp works fine but studio produced this error:
Error	TS1056	Accessors are only available when targeting ECMAScript 5 and higher.
Any ideas?

**Comment by nycdotnet** [comment]
@drag13 Do you mean building with grunt?  If you're using gulp, this is not the correct place to ask.  If the error is coming up in VS, you may wish to check the project properties (right-click on your project in VS and look at the TypeScript tag) or your tsconfig.json file.

**Comment by Drag13** [comment]
@nycdotnet  Sry, I just found this bug with very similar behavior. This is not related to the grunt. So just never mind and thanks for response.
