### ISSUE TITLE
Latest releases are missing a bugfix

### ISSUE THREAD

**Issue by rolego** [TypeStrong/grunt-ts#297]
The recently released versions on npm 5.0.1 and 5.1.0-beta.2 did not contain the changes made by https://github.com/TypeStrong/grunt-ts/pull/291

Since we're relying on this fix, we would appreciate if someone could have a look at it.

**Comment by nycdotnet** [comment]
I'll address it presently.  Not sure how it disappeared but it must have been my fault somewhere.  Thanks for the follow-up.

**Comment by nycdotnet** [comment]
I think I switched computers and didn't resync first or something equally stupid.  Sorry about that.  I am releasing 5.1.0 in the next few minutes which includes your fix for #291 plus a new test to ensure that the html features always get passed correctly.  I'm closing this ticket now - please re-open if not fixed in 5.1.0.
