### ISSUE TITLE
51 non-emit-preventing type warnings

### ISSUE THREAD

**Issue by ritox842** [TypeStrong/grunt-ts#356]
Hey all.

I'm trying to build my project with grunt but I`m getting the following error:

>> 1 syntax error  51 non-emit-preventing type warnings
>> Error: tsc return code: 2
Warning: Task "ts:default" failed. Use --force to continue.

I cant figure it out.
Can anyone help me?

**Comment by nycdotnet** [comment]
Hi,
You should be getting some additional error messages.  The count of errors doesn't really help troubleshoot this problem.  In the list of errors you got, look for which is the syntax error - that's the one you must fix to get the JS emit from TypeScript.  The rest are technically optional to fix since they don't prevent the emit; TypeScript is just warning you that it thinks there may be a problem with types not matching.
I'm going to close this issue since I don't expect this is a bug with grunt-ts.  If you disagree, please re-open and provide more info.  If you need help with getting started with a TypeScript error message, try searching StackOverflow for it.  Good luck!
