### ISSUE TITLE
Update to TypeScript v2

### ISSUE THREAD

**Issue by Izzmo** [TypeStrong/grunt-ts#388]
When will we have TypeScript v2 support for this extension? I don't see any pull requests related to it, or issues for that matter besides various tidbits.

**Comment by nycdotnet** [comment]
Unclear - hopefully soonish.

For now you can use the [Additional Flags](https://github.com/TypeStrong/grunt-ts#additionalflags) feature to support most of the TypeScript 2.1 stuff, and grunt-ts already supports using [any compiler you want](https://github.com/TypeStrong/grunt-ts#compiler).  Hopefully it shouldn't take more than a few minutes to get nearly everything working for you with TypeScript 2.1 and grunt-ts.

The main cause for the delay is there are some new TypeScript features in 2.x that are technically only supported via tsconfig.json (since they're arrays and that's awkward to pass on the command line so the TypeScript team doesn't support it).  So, we need to add support for it via grunt options and this is going to mean some major effort to switch our tsc calling mechanism to temporary tsconfig.json files.

**Comment by Izzmo** [comment]
Awesome, thanks for the response @nycdotnet, I'll try out those flags and see if I can get something working.

**Comment by Izzmo** [comment]
Closing.
